### ISSUE TITLE
Move to rebar3 ?

### ISSUE THREAD

**Issue by marco-m** [julienXX/slacker#15]
Salut Julien,

I have many improvements to the tests, because I wanted to add `rtm.start`. Since I am using rebar3, some changes I made broke running `rebar2 eunit`. Since rebar2 is deprecated, I think this is not a big deal. I can even update the rebar.config file to use only rebar3 syntax.

On the other hand, I don't have time to also keep backward compatibility with rebar2. I wanted to know, with the goal of contributing my changes, if you are OK with the idea of abandoning support for rebar2.

**Comment by julienXX** [comment]
Hi Marco,
Sure, let's be up to date and deprecate rebar2 for slacker.

**Comment by marco-m** [comment]
Very good then. I will post some PRs.

**Comment by julienXX** [comment]
Cool! Waiting for them :)
